In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [2]:
dataset=pd.read_csv('Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
X=np.array(dataset.drop(['Exited','CustomerId','Surname','RowNumber'],axis=1))

In [4]:
X.shape

(10000, 10)

In [5]:
Y=np.array(dataset['Exited'])

In [6]:
Y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [7]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X=LabelEncoder()
X[:,1]=labelencoder_X.fit_transform(X[:,1])

labelencoder_X_2=LabelEncoder()
X[:,2]=labelencoder_X_2.fit_transform(X[:,2])

#onehotencoder=OneHotEncoder(categorical_features=[1])
#X=onehotencoder

In [8]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
from sklearn.compose import ColumnTransformer
coltransformer=ColumnTransformer([('encoder',OneHotEncoder(),[1])],remainder='passthrough')

In [10]:
X=coltransformer.fit_transform(X)

In [11]:
X.shape

(10000, 12)

In [12]:
X = X[:, 1:]

In [13]:
print(X)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
sc=StandardScaler()

In [18]:
X_train=sc.fit_transform(X_train)

In [19]:
X_test=sc.fit_transform(X_test)

            Step 3- Let's Make an ANN

In [20]:
import keras 

Using TensorFlow backend.


import sequentia- initaize Neural Network and dense module that is required to build layer of our ANN

In [21]:
from keras.models import Sequential
from keras.layers import Dense

In [22]:
#Initializing the ANN- definging it as a sequence af layers. Either by defining the sequence of layers or either by defining the graph

In [23]:
#initializing ANN by sequence of layers

In [24]:
#Since our problem was of classification, our Neureal net will play the role of a classifier.

In [25]:
classifier=Sequential()

In [26]:
#We are now ready to add different layers to the ANN we just initialized

In [27]:
#Step 5

In [28]:
#We will now add input layer and hidden layers

In [29]:
# We will use Rectifier Activation Function for the input hidden layer and Sigmoif Function for the Output layer


In [30]:
#The rate by which the weights are updated are known as the Learning Rate

In [31]:
#Adding the input layer and first hidden layer. Dense Funcition helps us define which activation fuction we will use and how any i/p & Hidden layers we need to add and how the w=eights are updated

In [32]:
classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))

C:\Users\LaKgos01\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [33]:
#Output_dim is the number of nodes you want to add to the Hidden layer
#There is no rule of thumb on deciding how many nodes we want to add to the hidden layer.
#Tip= choose the number of nodes in the hidden layer as the avg of number of nodes in the input layer and the number of nodes in th eoutput layer. We can also experiment using parameter tuning

In [34]:
#init parameter is the step 1 in sthocastic gradint descent i.e. to randomly initlaize the weight to something close to 0 but not 0
#Actication- It is the activation function we need to use in the hidden layer

#input_dim= number of nodes in the imput layer. We will not need to specify if we are creating further hidden layers, since the first hidden layer will already be created, the next hidden layer will know what to expect/


Step 6

In [35]:
#We are now going to add the second hidden layer

In [36]:
classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))
#As this is the second hidden layer, we do not need to add the parameter input_din, as it knows what to expect from the previous hidden layer

C:\Users\LaKgos01\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


Step 7


In [37]:
#We have till now added 3 layers. We will now add output layer

In [38]:
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))
# we might want to have a different Activation function if we have more than 2 outcomes as the sigmoid fuction works on Probabilty

C:\Users\LaKgos01\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


Step 8

In [39]:
#Compile the ANN- i.e. applying Gradient Descent

In [40]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [41]:
#optimizer is the algorithm which will help in finding the best weights....this is nothing more than Stochastic gradient descent.
#Loss- Cost function of loss function...If the dependent variable has 2 outcomes, then it is called binary_crossentropy and if there are more than 2 outcomes, it will be categorical_crossentropy.
#metrics-critirion to evaluate the model......to improve the models performance.

#Setp 9 

In [42]:
#We will see the ANN in action and fit the ANN to the Training set

In [43]:
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.4948 - accuracy: 0.7954
Epoch 2/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.4280 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4234 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4193 - accuracy: 0.8086
Epoch 5/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.4159 - accuracy: 0.8256
Epoch 6/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.4143 - accuracy: 0.8296
Epoch 7/100
8000/8000 [==============================] - 1s 121us/step - loss: 0.4127 - accuracy: 0.8325
Epoch 8/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4115 - accuracy: 0.8319
Epoch 9/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4106 - accuracy: 0.8322
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 1s 124us/step - loss: 0.3964 - accuracy: 0.8370
Epoch 79/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.3961 - accuracy: 0.8370
Epoch 80/100
8000/8000 [==============================] - 1s 122us/step - loss: 0.3962 - accuracy: 0.8388
Epoch 81/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.3964 - accuracy: 0.8388
Epoch 82/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.3964 - accuracy: 0.8375
Epoch 83/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.3960 - accuracy: 0.8389
Epoch 84/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.3962 - accuracy: 0.8397
Epoch 85/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.3957 - accuracy: 0.8386
Epoch 86/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.3954 - accuracy: 0.8370
Epoch 87/100
8000/8000 [==============================] - 1

In [44]:
#batch_size= the number of repetitions after which the weights would be updated.
#epoch= th enumber of epochs(different Rounds)

Step 10 

In [45]:
#predict the Test set results.
# THe back can use the data to get the top 10% of people who could leave the bank

In [46]:
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)# to make the results in either true or false....True if >0.5 otherwise alse

In [47]:
from sklearn.metrics import confusion_matrix

In [48]:
cm=confusion_matrix(y_test,y_pred)

In [49]:
cm

array([[1512,   83],
       [ 215,  190]], dtype=int64)

In [50]:
customer=[]

Evaluating the ANN 

We trained our ANN twice, and obtained a different accuracy .This takes us to the bias variance trade off where the model we are trying to train a model which is not only accurate but also doesnt have much variance in the Accuracies that we obtain after training it several times


In [51]:
#hen we perform a same model in 2 different Test sets, we can get completely different accuracies, so we would not know which one to use.

In [52]:
#We can use K-fold Validation for the same. This will give us better idea of the Accuracy.

In [53]:
#Evaluate ANN. Implement k-fold...

In [54]:
#we used Keras for implementing classification and K-flod is a sklearn module.

In [55]:
#We will be able to include our k-fold validation in our Keras classifier. We will use Keras wrapper for the same.

In [56]:
from keras.wrappers.scikit_learn import KerasClassifier

In [57]:
from sklearn.model_selection import cross_val_score

In [58]:
def build_classifier():
    classifier=Sequential()
    classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))
    classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))
    classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))
    classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return classifier

In [59]:
global_classifier=build_classifier()

C:\Users\LaKgos01\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\LaKgos01\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
C:\Users\LaKgos01\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """


In [60]:
classifier_kfold=KerasClassifier(build_fn=build_classifier,batch_size=19,nb_epoch=100)
accuracies=cross_val_score(estimator=classifier_kfold,X=X_train, y=y_train,cv=10,n_jobs=-1)

In [61]:
accuracies

array([0.78625   , 0.79000002, 0.80000001, 0.78250003, 0.81625003,
       0.81      , 0.78750002, 0.79374999, 0.79874998, 0.79500002])

In [62]:
accuracies.mean()

0.7960000097751617

In [63]:
accuracies.var()

0.0001021249810459679

In [64]:
#Dropout Reularization- Solution for over fitting(we can notice this when we have large difference in accuracies in the Test set and the training set) in Deep learning....Overfitting can also be caught with High-Variance

In [65]:
#At each iteration of the training, some neurons are randomly disabled, to prevent them from being too dependent while training.....

In [66]:
from keras.layers import Dropout #We apply dropout to layers

In [67]:
classifier.add(Dropout(p=0.1))

C:\Users\LaKgos01\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  """Entry point for launching an IPython kernel.


In [68]:
def build_classifier():
    classifier=Sequential()
    classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))
    classifier.add(Dropout(p=0.1))
    
    
    classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))
    classifier.add(Dropout(p=0.1))
    
    classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))
    classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return classifier

In [69]:
classifier_kfold=KerasClassifier(build_fn=build_classifier,batch_size=19,nb_epoch=100)
accuracies=cross_val_score(estimator=classifier_kfold,X=X_train, y=y_train,cv=10,n_jobs=-1)

In [71]:
accuracies

array([0.78625   , 0.79000002, 0.80000001, 0.78250003, 0.81625003,
       0.81      , 0.78750002, 0.79374999, 0.79874998, 0.79500002])

In [72]:
accuracies.mean()

0.7960000097751617

Tuning the ANN

In [74]:
#We have 2 type of parameters- weights(changed) and the ones, which are fixed- Like npo. of neurons, the no. of Epochs., etc..

In [75]:
#Parameter tuning consists of finding the appropriate values for these parameter- We are going to do this with a Technique called Grid Search

In [76]:
#We will use the KerasClassifier library itself for implementing Grid Search

In [77]:
from sklearn.model_selection import GridSearchCV

In [80]:
def build_classifier(optimizer):
    classifier=Sequential()
    classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))
    classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))
    classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))
    classifier.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
    return classifier

In [85]:
classifier_GridSearch=KerasClassifier(build_fn=build_classifier#we are going ot tune the epoch and nodes and will include it in the GridSearch
parameters={'batch_size':[20,30],
            'nb_epoch':[50,100,200],
           'optimizer':['adam','rmsprop']}

grid_search=GridSearchCV(estimator=classifier_GridSearch,param_grid=parameters,scoring='accuracy',cv=10)
#accuracies=cross_val_score(estimator=classifier_kfold,X=X_train, y=y_train,cv=10,n_jobs=-1)

grid_search=grid_search.fit(X_train,y_train)
best_parameters=grid_search.best_parameters
best_accuracy=grid_search.best_accuracy

C:\Users\LaKgos01\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\LaKgos01\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
C:\Users\LaKgos01\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """


Epoch 1/1
7200/7200 [==============================] - 1s 95us/step - loss: 0.5297 - accuracy: 0.7971
Epoch 1/1
7200/7200 [==============================] - 1s 80us/step - loss: 0.5306 - accuracy: 0.7967
Epoch 1/1
7200/7200 [==============================] - 1s 101us/step - loss: 0.5376 - accuracy: 0.7946
Epoch 1/1
7200/7200 [==============================] - 1s 86us/step - loss: 0.5257 - accuracy: 0.7969
Epoch 1/1
7200/7200 [==============================] - 1s 78us/step - loss: 0.5257 - accuracy: 0.7935
Epoch 1/1
7200/7200 [==============================] - 1s 109us/step - loss: 0.5381 - accuracy: 0.7939
Epoch 1/1
7200/7200 [==============================] - 1s 96us/step - loss: 0.5564 - accuracy: 0.7950
Epoch 1/1
7200/7200 [==============================] - 1s 78us/step - loss: 0.5296 - accuracy: 0.7958
Epoch 1/1
7200/7200 [==============================] - 1s 75us/step - loss: 0.5259 - accuracy: 0.7956
Epoch 1/1
7200/7200 [==============================] - 1s 77us/step - loss: 0.55

7200/7200 [==============================] - 0s 56us/step - loss: 0.5898 - accuracy: 0.7958
Epoch 1/1
7200/7200 [==============================] - 0s 62us/step - loss: 0.6092 - accuracy: 0.7950
Epoch 1/1
7200/7200 [==============================] - 0s 55us/step - loss: 0.5976 - accuracy: 0.7960
Epoch 1/1
7200/7200 [==============================] - 0s 55us/step - loss: 0.6022 - accuracy: 0.7928
Epoch 1/1
7200/7200 [==============================] - 0s 54us/step - loss: 0.5796 - accuracy: 0.7974
Epoch 1/1
7200/7200 [==============================] - 0s 66us/step - loss: 0.5599 - accuracy: 0.7939
Epoch 1/1
7200/7200 [==============================] - 0s 58us/step - loss: 0.5712 - accuracy: 0.7946
Epoch 1/1
7200/7200 [==============================] - 0s 58us/step - loss: 0.6128 - accuracy: 0.7951
Epoch 1/1
7200/7200 [==============================] - 0s 55us/step - loss: 0.5960 - accuracy: 0.7956
Epoch 1/1
7200/7200 [==============================] - 0s 54us/step - loss: 0.5823 - accurac

AttributeError: 'GridSearchCV' object has no attribute 'best_parameter'

In [87]:
best_accuracy

NameError: name 'best_accuracy' is not defined